# Generated by Django 4.0.4 on 2022-06-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('gp_behaves_like_sub_ledger', models.BooleanField(default=False)),
                ('nett_debit_credit_bal_reporting', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('method_to_allocate_usd_purchase', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=225)),
                ('ledger_alias', models.CharField(max_length=225)),
                ('ledger_opening_bal', models.CharField(max_length=225)),
                ('ledger_type', models.CharField(max_length=225)),
                ('type_of_duty', models.CharField(max_length=225)),
                ('percent_of_calculation', models.CharField(max_length=225)),
                ('maintain_bal_bill', models.CharField(max_length=225)),
                ('credit_days_during_voucher_entry', models.CharField(max_length=225)),
                ('default_cr_peroid', models.CharField(max_length=225)),
                ('provide_banking_details', models.BooleanField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.groupmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.AlterField(
            model_name='contra',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='groups',
        ),
        migrations.AlterField(
            model_name='contra',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.groupmodel'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledgermodel'),
        ),
        migrations.DeleteModel(
            name='ledger',
        ),
    ]
