# Generated by Django 4.0.4 on 2022-07-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_alter_contra_account_alter_contra_particulars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=225)),
                ('ledger_alias', models.CharField(max_length=225)),
                ('group_under', models.CharField(max_length=225)),
                ('ledger_opening_bal', models.CharField(max_length=225)),
                ('ledger_type', models.CharField(max_length=225)),
                ('provide_banking_details', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='ledgermodel',
            name='group',
        ),
        migrations.AddField(
            model_name='contra',
            name='instdate',
            field=models.CharField(default='24Mar2022', max_length=225),
        ),
        migrations.AddField(
            model_name='contra',
            name='instno',
            field=models.PositiveIntegerField(default=5656),
        ),
        migrations.AddField(
            model_name='contra',
            name='transactiontype',
            field=models.CharField(choices=[('cheque/dd', 'Cheque/dd'), ('atm', 'Atm'), ('card', 'Card'), ('cash', 'Cash'), ('e-fund-transfer', 'E-fund-transfer'), ('others', 'Others')], default='cheque/dd', max_length=30),
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
        migrations.AlterField(
            model_name='contra',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountled', to='tallyapp.ledger'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partled', to='tallyapp.ledger'),
        ),
        migrations.DeleteModel(
            name='LedgerModel',
        ),
    ]
