# Generated by Django 4.0.4 on 2022-07-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_ledger_remove_ledgermodel_group_contra_instdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contra',
            name='narration',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=30)),
                ('transactiontype', models.CharField(choices=[('cheque/dd', 'Cheque/dd'), ('atm', 'Atm'), ('card', 'Card'), ('cash', 'Cash'), ('e-fund-transfer', 'E-fund-transfer'), ('others', 'Others')], default='cheque/dd', max_length=30)),
                ('instno', models.PositiveIntegerField(default=5656)),
                ('instdate', models.CharField(default='24Mar2022', max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('no', models.PositiveIntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recacc', to='tallyapp.ledger')),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recled', to='tallyapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=30)),
                ('transactiontype', models.CharField(choices=[('cheque/dd', 'Cheque/dd'), ('atm', 'Atm'), ('card', 'Card'), ('cash', 'Cash'), ('e-fund-transfer', 'E-fund-transfer'), ('others', 'Others')], default='cheque/dd', max_length=30)),
                ('instno', models.PositiveIntegerField(default=5656)),
                ('instdate', models.CharField(default='24Mar2022', max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('no', models.PositiveIntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payacc', to='tallyapp.ledger')),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payled', to='tallyapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(choices=[('cheque/dd', 'Cheque/dd'), ('atm', 'Atm'), ('card', 'Card'), ('cash', 'Cash'), ('e-fund-transfer', 'E-fund-transfer'), ('others', 'Others')], default='cheque/dd', max_length=30)),
                ('instno', models.PositiveIntegerField(default=5656)),
                ('instdate', models.CharField(default='24Mar2022', max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('no', models.PositiveIntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jouacc', to='tallyapp.ledger')),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jouled', to='tallyapp.ledger')),
            ],
        ),
    ]
