# Generated by Django 4.0.4 on 2022-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0007_sales_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
